name: MERN CI

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      # cache both package-locks
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      # ---------- Backend ----------
      - name: Install backend
        working-directory: backend
        run: npm ci

      - name: Test backend
        working-directory: backend
        run: npm test --if-present

      # ---------- Frontend ----------
      - name: Install frontend
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build --if-present

      # (optional) save build artifact (e.g., for deploy step)
      - name: Upload frontend build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
